root: true
env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      semi: false
      arrowParens: avoid
    - usePrettierrc: false
